
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri Apr 07 16:19:32 CEST 2023
//----------------------------------------------------

package ditto.parser;

/** CUP generated class containing symbol constants. */
public class TokenKind {
  /* terminals */
  public static final int OTHERWISE = 40;
  public static final int CASE = 38;
  public static final int NOT_EQUAL = 7;
  public static final int GREATER = 9;
  public static final int INT = 45;
  public static final int ARRAY = 47;
  public static final int REF = 54;
  public static final int LESS = 10;
  public static final int FOR = 33;
  public static final int MINUS = 3;
  public static final int MATCH = 37;
  public static final int IS = 39;
  public static final int NOT = 29;
  public static final int SEMICOLON = 19;
  public static final int AND = 27;
  public static final int CLOSE_PAR = 14;
  public static final int OPEN_PAR = 13;
  public static final int OR = 28;
  public static final int BOOL = 46;
  public static final int COMMA = 21;
  public static final int DIV = 5;
  public static final int LESS_EQUAL = 12;
  public static final int OPEN_CURLY = 17;
  public static final int PLUS = 2;
  public static final int ASSIGN = 26;
  public static final int IF = 31;
  public static final int PTR = 48;
  public static final int DOT = 22;
  public static final int EOF = 0;
  public static final int RETURN = 36;
  public static final int EQUAL = 8;
  public static final int TRUE = 57;
  public static final int BY = 53;
  public static final int GREATER_EQUAL = 11;
  public static final int NEW = 55;
  public static final int error = 1;
  public static final int MOD = 6;
  public static final int CLOSE_BRACKET = 16;
  public static final int OPEN_BRACKET = 15;
  public static final int FROM = 51;
  public static final int IMPORT = 35;
  public static final int MODULE = 44;
  public static final int TIMES = 4;
  public static final int QUADOT = 23;
  public static final int COLON = 20;
  public static final int CLOSE_CURLY = 18;
  public static final int ELSE = 32;
  public static final int FUNC = 30;
  public static final int IDEN = 59;
  public static final int TO = 52;
  public static final int WHILE = 34;
  public static final int PUBLIC = 50;
  public static final int THEN = 43;
  public static final int END = 41;
  public static final int NAT = 56;
  public static final int AT = 24;
  public static final int FALSE = 58;
  public static final int STRUCT = 49;
  public static final int R_ARROW = 25;
  public static final int DO = 42;
}

