
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Mar 27 20:11:41 CEST 2023
//----------------------------------------------------

package ditto.parser;

/** CUP generated class containing symbol constants. */
public class TokenKind {
  /* terminals */
  public static final int OTHERWISE = 37;
  public static final int CASE = 31;
  public static final int NOT_EQUAL = 9;
  public static final int GREATER = 8;
  public static final int ARRAY = 49;
  public static final int REF = 48;
  public static final int LESS = 7;
  public static final int FOR = 26;
  public static final int MINUS = 3;
  public static final int MATCH = 30;
  public static final int NOT = 15;
  public static final int SEMICOLON = 33;
  public static final int IS = 32;
  public static final int AND = 13;
  public static final int CLOSE_PAR = 17;
  public static final int OPEN_PAR = 16;
  public static final int OR = 14;
  public static final int COMMA = 34;
  public static final int DIV = 5;
  public static final int LESS_EQUAL = 12;
  public static final int PLUS = 2;
  public static final int ASSIGN = 22;
  public static final int IF = 24;
  public static final int PTR = 47;
  public static final int EOF = 0;
  public static final int RETURN = 29;
  public static final int EQUAL = 10;
  public static final int BY = 46;
  public static final int TRUE = 19;
  public static final int GREATER_EQUAL = 11;
  public static final int NEW = 50;
  public static final int error = 1;
  public static final int MOD = 6;
  public static final int FROM = 44;
  public static final int IMPORT = 28;
  public static final int MODULE = 41;
  public static final int TIMES = 4;
  public static final int QUADOT = 35;
  public static final int ELSE = 25;
  public static final int FUNC = 23;
  public static final int TO = 45;
  public static final int IDEN = 21;
  public static final int WHILE = 27;
  public static final int PUBLIC = 43;
  public static final int THEN = 40;
  public static final int END = 38;
  public static final int NAT = 18;
  public static final int FALSE = 20;
  public static final int STRUCT = 42;
  public static final int R_ARROW = 36;
  public static final int DO = 39;
}

