package ditto.ast;

public enum Kind {
    // TERMINALES
    BOOL, NAT, PLUS, MINUS, TIMES, DIV, MOD, LESS, GREATER, NOT_EQUAL, EQUAL,
         GREATER_EQUAL, LESS_EQUAL, AND, OR, NOT, OPEN_PAR, CLOSE_PAR,

    // NO TERMINALES
    S, EXPR, DISJUNCTION, CONJUNCTION, NEGATION, EQUALITY, COMPARISON, TERM, FACTOR, UNARY, PRIMARY;
}
