
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri Mar 03 12:04:18 UTC 2023
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PCIERRE = 11;
  public static final int MENOS = 5;
  public static final int EQUAL = 22;
  public static final int GREATER = 20;
  public static final int CONCAT = 15;
  public static final int IDEN = 2;
  public static final int LMAP = 17;
  public static final int POR = 6;
  public static final int NUM = 3;
  public static final int COMA = 9;
  public static final int LFILTER = 18;
  public static final int EOF = 0;
  public static final int UNEQUAL = 21;
  public static final int LREDUCE = 16;
  public static final int LEND = 13;
  public static final int LBEGIN = 12;
  public static final int DIV = 7;
  public static final int PAP = 10;
  public static final int PRINT = 14;
  public static final int error = 1;
  public static final int ASSIGN = 8;
  public static final int MAS = 4;
  public static final int LESS = 19;
}

