name: Build and test lexer and parser

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build all
        run: ./run.sh build all
        
      - name: Test lexer
        run: ./run.sh lexer
        
      - name: Test parser
        run: ./run.sh parser

  AST:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build all
        run: ./run.sh build all
        
      - name: Test AST
        run: ./run.sh test
