name: Build and test lexer and parser

on: [push]

jobs:
  build:
    name: Build lexer and parser
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build all
        run: ./run.sh build all
        
  lexer:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Test lexer
        run: ./run.sh lexer
        
  parser:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Test parser
        run: ./run.sh parser
