name: Build and test all

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build all
        run: ./run.sh build all

      - name: Test AST
        run: export DO_NOT_COMPILE=1 && ./run.sh test ast all
        
      - name: Test Bindings
        run: export DO_NOT_COMPILE=1 && ./run.sh test bind all
        
      - name: Test Typecheck
        run: export DO_NOT_COMPILE=1 && ./run.sh test typecheck all

      - name: Test Typesize
        run: export DO_NOT_COMPILE=1 && ./run.sh test typesize all

      - name: Test Offsets
        run: export DO_NOT_COMPILE=1 && ./run.sh test offsets all

      - name: Test code
        run: export DO_NOT_COMPILE=1 && ./run.sh test code all